"""GENERATED by scripts/gen_page_vocab.py from src/june_service/page_vocab.json — DO NOT EDIT.

The page vocabulary (connector copy). Edit the JSON and re-run the generator;
tests/architecture/test_page_vocab_single_source.py fails the build if this file drifts.
"""
from __future__ import annotations

from typing import Any

SOURCE_SHA = "deca65b626839cde"

VOCAB: dict[str, Any] = {'version': 1,
 'colors': ['slate',
            'gray',
            'brown',
            'red',
            'rose',
            'orange',
            'amber',
            'yellow',
            'lime',
            'green',
            'teal',
            'cyan',
            'sky',
            'blue',
            'indigo',
            'purple',
            'fuchsia',
            'pink'],
 'callout_variants': ['note', 'info', 'tip', 'success', 'warning', 'danger'],
 'todo_flags': ['high', 'low', 'blocked'],
 'covers': ['auto',
            'dawn',
            'ocean',
            'aurora',
            'peach',
            'forest',
            'ink',
            'sunset',
            'lilac',
            'mint',
            'ember'],
 'block_types': ['paragraph',
                 'heading_1',
                 'heading_2',
                 'heading_3',
                 'bulleted',
                 'numbered',
                 'todo',
                 'todo_done',
                 'quote',
                 'callout',
                 'code',
                 'divider',
                 'embed'],
 'legacy_block_types': ['text', 'heading'],
 'block_type_fallback': 'text',
 'block_type_aliases': {'p': 'paragraph',
                        'h1': 'heading_1',
                        'h2': 'heading_2',
                        'h3': 'heading_3',
                        'heading1': 'heading_1',
                        'heading2': 'heading_2',
                        'heading3': 'heading_3',
                        'bullet': 'bulleted',
                        'bullets': 'bulleted',
                        'bullet_list': 'bulleted',
                        'bulleted_list': 'bulleted',
                        'ul': 'bulleted',
                        'unordered': 'bulleted',
                        'number': 'numbered',
                        'numbered_list': 'numbered',
                        'ordered': 'numbered',
                        'ol': 'numbered',
                        'task': 'todo',
                        'checkbox': 'todo',
                        'to_do': 'todo',
                        'to-do': 'todo',
                        'blockquote': 'quote',
                        'note': 'callout',
                        'aside': 'callout',
                        'pre': 'code',
                        'snippet': 'code',
                        'hr': 'divider',
                        'rule': 'divider',
                        'separator': 'divider',
                        'image': 'embed',
                        'img': 'embed',
                        'media': 'embed',
                        'link': 'embed',
                        'photo': 'embed',
                        'picture': 'embed'},
 'illustrations': [{'name': 'doro-wave',
                    'label': 'Doro waves',
                    'group': 'doro',
                    'hint': 'A hello — welcomes, intros'},
                   {'name': 'doro-think',
                    'label': 'Doro thinks',
                    'group': 'doro',
                    'hint': 'Open questions, decisions pending'},
                   {'name': 'doro-read',
                    'label': 'Doro reads',
                    'group': 'doro',
                    'hint': 'Notes, research, a reading list'},
                   {'name': 'doro-cheer',
                    'label': 'Doro cheers',
                    'group': 'doro',
                    'hint': 'Shipped, done, celebrated'},
                   {'name': 'doro-sleep',
                    'label': 'Doro rests',
                    'group': 'doro',
                    'hint': 'Paused, parked, later'},
                   {'name': 'graph',
                    'label': 'Graph',
                    'group': 'shapes',
                    'hint': 'Nodes and edges — the knowledge graph'},
                   {'name': 'orbit',
                    'label': 'Orbit',
                    'group': 'shapes',
                    'hint': 'A system around a centre'},
                   {'name': 'sparkles',
                    'label': 'Sparkles',
                    'group': 'shapes',
                    'hint': 'New, magic, AI'},
                   {'name': 'mesh',
                    'label': 'Mesh',
                    'group': 'shapes',
                    'hint': 'A soft gradient field — section breaks'},
                   {'name': 'waves',
                    'label': 'Waves',
                    'group': 'shapes',
                    'hint': 'Flow, rhythm, cadence'},
                   {'name': 'rocket',
                    'label': 'Rocket',
                    'group': 'scenes',
                    'hint': 'Launches and milestones'},
                   {'name': 'idea',
                    'label': 'Idea',
                    'group': 'scenes',
                    'hint': 'A lightbulb — proposals, brainstorms'},
                   {'name': 'checklist',
                    'label': 'Checklist',
                    'group': 'scenes',
                    'hint': 'Plans, runbooks, to-dos'},
                   {'name': 'mountain',
                    'label': 'Mountain',
                    'group': 'scenes',
                    'hint': 'Goals and the road to them'},
                   {'name': 'calendar',
                    'label': 'Calendar',
                    'group': 'scenes',
                    'hint': 'Dates, schedules, deadlines'},
                   {'name': 'compass',
                    'label': 'Compass',
                    'group': 'scenes',
                    'hint': 'Direction, strategy, principles'}],
 'illustration_sizes': ['s', 'm', 'l'],
 'illustration_default_size': 'm',
 'media_aligns': ['left', 'center', 'right'],
 'media_align_aliases': {'middle': 'center', 'centre': 'center'},
 'media_width_min': 5,
 'media_width_max': 100,
 'media_angle_max': 45,
 'media_nudge_max': 300,
 'media_schemes': ['http://', 'https://', 'data:image/', 'june://files/'],
 'space_min': 0,
 'space_max': 120,
 'icon_max_utf16': 8,
 'controls': ['select', 'multi', 'progress', 'date', 'button', 'illustration'],
 'progress_shapes': ['bar', 'ring']}

COLORS: frozenset[str] = frozenset(VOCAB["colors"])
CALLOUT_VARIANTS: frozenset[str] = frozenset(VOCAB["callout_variants"])
TODO_FLAGS: frozenset[str] = frozenset(VOCAB["todo_flags"])
COVERS: frozenset[str] = frozenset(VOCAB["covers"])
BLOCK_TYPES: frozenset[str] = frozenset(VOCAB["block_types"]) | frozenset(VOCAB["legacy_block_types"])
BLOCK_TYPE_ALIASES: dict[str, str] = dict(VOCAB["block_type_aliases"])
BLOCK_TYPE_FALLBACK: str = VOCAB["block_type_fallback"]
ILLUSTRATION_NAMES: tuple[str, ...] = tuple(i["name"] for i in VOCAB["illustrations"])
ILLUSTRATION_SIZES: tuple[str, ...] = tuple(VOCAB["illustration_sizes"])
MEDIA_SCHEMES: tuple[str, ...] = tuple(VOCAB["media_schemes"])
SPACE_MIN: int = VOCAB["space_min"]
SPACE_MAX: int = VOCAB["space_max"]
ICON_MAX_UTF16: int = VOCAB["icon_max_utf16"]


def utf16_len(s: str) -> int:
    """Length as JavaScript's ``String.length`` counts it (UTF-16 code units) — the app's icon
    rule. Python's ``len`` counts code points, so an emoji outside the BMP is 1 here and 2 there;
    counting the same way in every runtime is what stops one side accepting what the other drops."""
    return len(s.encode("utf-16-le", "surrogatepass")) // 2     # a lone surrogate is 1 unit, as in JS


def icon_ok(s: str) -> bool:
    """An icon the app will draw: non-blank after trimming, at most ICON_MAX_UTF16 units."""
    t = s.strip()
    return bool(t) and utf16_len(t) <= ICON_MAX_UTF16
